"""avatar hash added to User model

Revision ID: 821c9a7f792b
Revises: b86e861d8baf
Create Date: 2021-06-19 07:24:53.331439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '821c9a7f792b'
down_revision = 'b86e861d8baf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    # ### end Alembic commands ###
